[package]
name = "sg1"
version = "0.10.0"
edition = "2021"

authors = ["Shane Vitarana <s@noreply.publicawesome.com>"]
description = "Definition and types for the SG1 interface"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/stargaze-contracts"
homepage = "https://stargaze.zone"

[dependencies]
cosmwasm-std = { version = "1.0.0-beta7" }
cw-utils = "0.13.1"
cw721 = "0.13.1"
cw721-base = { version = "0.13.1", features = ["library"] }
schemars = "0.8.8"
serde = { version = "1.0.133", default-features = false, features = ["derive"] }
thiserror = "1.0.30"

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta7" }
