[package]
name = "sg-std"
version = "0.1.0"
edition = "2021"

authors = ["Jorge Hernandez <jorge@publicawesome.com>"]
description = "Bindings for CosmWasm contracts to call into custom modules of Stargaze"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/contracts"
homepage = "https://stargaze.zone"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { version = "1.0.0-beta" }
schemars = "0.8.8"
serde = { version = "1.0.133", default-features = false, features = ["derive"] }